on:
  schedule:
  - cron: '0 */4 * * *'
  push:
    branches:
    - master
  pull_request:
    paths:
    - .github/actions/prepare/action.yml
    - .github/workflows/e2e-svelte-kit-workflow.yml
    - scripts/e2e-setup-ci.sh

name: 'E2E SvelteKit'
jobs:
  chore:
    name: 'Validating SvelteKit'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - uses: ./.github/actions/prepare

    - name: 'Running the integration test'
      run: |
        source scripts/e2e-setup-ci.sh

        # TODO: Remove once https://github.com/yarnpkg/berry/blob/bd146ccddf95aae9c99c0c48d86b1d8997f1dccf/scripts/e2e-setup-ci.sh#L31-L38 is fixed
        YARN_PNP_ENABLE_ESM_LOADER=true

        yes | yarn create svelte@next my-app && cd my-app
        yarn
        yarn build
